import { useState } from "react";
import jsPDF from "jspdf";
import type { ScanResult, Issue } from "../types";
interface ExportButtonProps {
  result: ScanResult;
  score: number;
  url: string;
  title: string;
}
const IMPACT_COLORS: Record<string, [number, number, number]> = {
  critical: [255, 68, 68],
  serious: [255, 136, 0],
  moderate: [245, 158, 11],
  minor: [136, 136, 170],
};

export default function ExportButton({
  result,
  score,
  url,
  title,
}: ExportButtonProps) {
  const [generating, setGenerating] = useState(false);

  const handleExport = async () => {
    setGenerating(true);
    // Small delay so the button feedback feels real
    await new Promise((r) => setTimeout(r, 400));

    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 48;
    let y = 0;

    // ── Cover page ────────────────────────────────────────────
    doc.setFillColor(10, 10, 15);
    doc.rect(0, 0, pageWidth, pageHeight, "F");

    doc.setFillColor(124, 106, 247);
    doc.circle(pageWidth / 2, 140, 36, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(28);
    doc.text("P", pageWidth / 2, 150, { align: "center" });

    doc.setFontSize(26);
    doc.setTextColor(240, 240, 248);
    doc.text("Accessibility Audit Report", pageWidth / 2, 210, {
      align: "center",
    });

    doc.setFontSize(12);
    doc.setTextColor(136, 136, 170);
    doc.text(title || url, pageWidth / 2, 236, {
      align: "center",
      maxWidth: pageWidth - 100,
    });
    doc.text(url, pageWidth / 2, 254, {
      align: "center",
      maxWidth: pageWidth - 100,
    });

    // Score circle
    const scoreColor: [number, number, number] =
      score >= 80
        ? [0, 212, 170]
        : score >= 50
          ? [245, 158, 11]
          : [255, 107, 107];
    doc.setDrawColor(...scoreColor);
    doc.setLineWidth(3);
    doc.circle(pageWidth / 2, 350, 50, "S");
    doc.setFontSize(32);
    doc.setTextColor(...scoreColor);
    doc.text(String(score), pageWidth / 2, 360, { align: "center" });
    doc.setFontSize(10);
    doc.setTextColor(136, 136, 170);
    doc.text("ACCESSIBILITY SCORE", pageWidth / 2, 425, { align: "center" });

    // Summary stats
    const statY = 470;
    const stats = [
      {
        label: "Issues",
        value: result.violations.length,
        color: [255, 107, 107] as [number, number, number],
      },
      {
        label: "Passed",
        value: result.passes.length,
        color: [0, 212, 170] as [number, number, number],
      },
      {
        label: "Warnings",
        value: result.incomplete.length,
        color: [245, 158, 11] as [number, number, number],
      },
    ];
    const statWidth = (pageWidth - margin * 2) / 3;
    stats.forEach((s, i) => {
      const x = margin + statWidth * i + statWidth / 2;
      doc.setFontSize(20);
      doc.setTextColor(...s.color);
      doc.text(String(s.value), x, statY, { align: "center" });
      doc.setFontSize(9);
      doc.setTextColor(136, 136, 170);
      doc.text(s.label.toUpperCase(), x, statY + 16, { align: "center" });
    });

    doc.setFontSize(9);
    doc.setTextColor(85, 85, 112);
    doc.text(
      `Generated by Phantom · ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`,
      pageWidth / 2,
      pageHeight - 40,
      { align: "center" },
    );

    // ── Issues pages ──────────────────────────────────────────
    doc.addPage();
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, pageWidth, pageHeight, "F");
    y = margin;

    doc.setTextColor(20, 20, 30);
    doc.setFontSize(18);
    doc.text("Accessibility Issues", margin, y);
    y += 8;
    doc.setDrawColor(230, 230, 235);
    doc.line(margin, y, pageWidth - margin, y);
    y += 28;

    const addNewPageIfNeeded = (needed: number) => {
      if (y + needed > pageHeight - margin) {
        doc.addPage();
        doc.setFillColor(255, 255, 255);
        doc.rect(0, 0, pageWidth, pageHeight, "F");
        y = margin;
      }
    };

    const renderIssue = (issue: Issue, index: number) => {
      addNewPageIfNeeded(90);

      const color = IMPACT_COLORS[issue.impact] ?? [136, 136, 170];

      // Severity badge
      doc.setFillColor(...color);
      doc.roundedRect(margin, y, 70, 16, 3, 3, "F");
      doc.setFontSize(8);
      doc.setTextColor(255, 255, 255);
      doc.text(issue.impact.toUpperCase(), margin + 35, y + 11, {
        align: "center",
      });

      // Issue number
      doc.setFontSize(9);
      doc.setTextColor(136, 136, 170);
      doc.text(`#${index + 1}`, pageWidth - margin, y + 11, { align: "right" });

      y += 26;

      // Title
      doc.setFontSize(12);
      doc.setTextColor(20, 20, 30);
      const titleLines = doc.splitTextToSize(
        issue.help,
        pageWidth - margin * 2,
      );
      doc.text(titleLines, margin, y);
      y += titleLines.length * 14 + 4;

      // Description
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 120);
      const descLines = doc.splitTextToSize(
        issue.description,
        pageWidth - margin * 2,
      );
      doc.text(descLines, margin, y);
      y += descLines.length * 13 + 6;

      // Affected elements
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 170);
      doc.text(
        `${issue.nodes} element${issue.nodes !== 1 ? "s" : ""} affected · Rule: ${issue.id}`,
        margin,
        y,
      );
      y += 24;

      doc.setDrawColor(240, 240, 245);
      doc.line(margin, y, pageWidth - margin, y);
      y += 20;
    };

    if (result.violations.length === 0) {
      doc.setFontSize(12);
      doc.setTextColor(0, 212, 170);
      doc.text("🎉 No accessibility issues found!", margin, y);
    } else {
      result.violations.forEach(renderIssue);
    }

    // ── Footer page numbers ───────────────────────────────────
    const totalPages = doc.getNumberOfPages();
    for (let i = 2; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(180, 180, 190);
      doc.text(
        `Phantom Accessibility Report — Page ${i - 1} of ${totalPages - 1}`,
        pageWidth / 2,
        pageHeight - 24,
        { align: "center" },
      );
    }

    // ── Save ──────────────────────────────────────────────────
    const safeHost = (() => {
      try {
        return new URL(url).hostname.replace(/\./g, "-");
      } catch {
        return "report";
      }
    })();
    doc.save(`phantom-report-${safeHost}.pdf`);

    setGenerating(false);
  };

  return (
    <button
      onClick={handleExport}
      disabled={generating}
      style={{
        width: "100%",
        padding: "10px 16px",
        background: "rgba(0,212,170,0.1)",
        border: "1px solid rgba(0,212,170,0.3)",
        borderRadius: 10,
        color: "#00d4aa",
        fontSize: 13,
        fontWeight: 600,
        cursor: generating ? "wait" : "pointer",
        fontFamily: "inherit",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        transition: "all 0.2s",
        opacity: generating ? 0.7 : 1,
      }}
    >
      {generating ? <>⏳ Generating PDF...</> : <>📄 Export PDF report</>}
    </button>
  );
}
